services:
  app:
    container_name: mobileModule
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/mobileModule
    command: bash -c "umask 000 && pnpm i --frozen-lockfile && chmod 777 -R /mobileModule/node_modules && pnpm lint && pnpm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
